apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: daily-backup
  annotations:
    field.cattle.io/description: Recurring backup at midnight
    #  key: string
  labels:
    {}
    #  key: string
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 10
  schedule: '@midnight'
